### PR TITLE
ft-contact-page

### PR DESCRIPTION
**Pull request by bertinNDAYISHIMIYE**
Screen Shot 2020-11-03 at 09 12 52

### CODE REVIEW

**Review by mukunzidd — CHANGES_REQUESTED** [review]
Can you swap the white icon place holder with actual icons?

**Comment by bertinNDAYISHIMIYE** [comment]
Done adding icons

**Review by mukunzidd — CHANGES_REQUESTED** [review]
Try something like font-awesome these icons look as if they are from two different planet.

**Comment by bertinNDAYISHIMIYE** [comment]
changed icons

**Review by mukunzidd — APPROVED** [review]

**Pull request merged**
